### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dovy** [dvcrn/exkit#1]
Is it over?

**Comment by dvcrn** [comment]
I'm currently not working with extensions but still stand behind the idea. But yes, in it's current state, this project is currently not being maintained anymore.

I'm still hoping to pick it up at a later point but if you need something like this, please feel free to just add on top of the existing code base. What has been written so far _should_ still work.

**Comment by dovy** [comment]
What browsers did you end up supporting? Safari as well or just firefox, chrome and opera?
